capstone) sustaincap@raspberrypi:~/Capstone $ pip install --no-build-isolation numpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy
  Using cached numpy-2.2.5.tar.gz (20.3 MB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      + /home/sustaincap/Capstone/capstone/bin/python3 /tmp/pip-install-bd5l6pkm/numpy_1b1638b8251d4387a67738849319052b/vendored-meson/meson/meson.py setup /tmp/pip-install-bd5l6pkm/numpy_1b1638b8251d4387a67738849319052b /tmp/pip-install-bd5l6pkm/numpy_1b1638b8251d4387a67738849319052b/.mesonpy-0gedruxw -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-bd5l6pkm/numpy_1b1638b8251d4387a67738849319052b/.mesonpy-0gedruxw/meson-python-native-file.ini
      The Meson build system
      Version: 1.5.2
      Source dir: /tmp/pip-install-bd5l6pkm/numpy_1b1638b8251d4387a67738849319052b
      Build dir: /tmp/pip-install-bd5l6pkm/numpy_1b1638b8251d4387a67738849319052b/.mesonpy-0gedruxw
      Build type: native build
      Project name: NumPy
      Project version: 2.2.5
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      
      ../meson.build:1:0: ERROR: Unknown compiler(s): [['cython'], ['cython3']]
      The following exception(s) were encountered:
      Running `cython -V` gave "[Errno 2] No such file or directory: 'cython'"
      Running `cython3 -V` gave "[Errno 2] No such file or directory: 'cython3'"
      
      A full log can be found at /tmp/pip-install-bd5l6pkm/numpy_1b1638b8251d4387a67738849319052b/.mesonpy-0gedruxw/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
